---
# tasks file for myapache
 - name: "Installing httpd"
   package:
           name: "httpd"
           state: present

 - name: "Installing php"
   package:
           name: "php"
           state: present

 - name: "copying the file"
   copy:
           src: "/root/index.php"
           dest: "/var/www/html/"



 - name: "Handling the firewall"
   firewalld:

           state: enabled
           port: 80/tcp
           permanent: yes

 - name: "Starting the service"
   service:
           name: "httpd"
           state: started


